// Same-origin copies of runtime assets because the CSP allows no CDN. Outputs are gitignored.
import { cpSync, existsSync, mkdirSync, readdirSync, rmSync, statSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const webRoot = path.resolve(here, "..");
const repoRoot = path.resolve(webRoot, "../..");
const publicDir = path.join(webRoot, "public");
const require = createRequire(path.join(webRoot, "package.json"));

function pkgDir(name, from = require) {
  return path.dirname(from.resolve(`${name}/package.json`));
}

function copy(from, to, filter) {
  if (!existsSync(from)) throw new Error(`Missing ${from}`);
  mkdirSync(path.dirname(to), { recursive: true });
  cpSync(from, to, { recursive: true, filter: filter ?? (() => true) });
}

function sizeOf(dir) {
  let total = 0;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    total += entry.isDirectory() ? sizeOf(p) : statSync(p).size;
  }
  return total;
}

const vendor = path.join(publicDir, "vendor");
rmSync(vendor, { recursive: true, force: true });

const pdfjs = pkgDir("pdfjs-dist");
const pdfjsOut = path.join(vendor, "pdfjs");
// Served as .js: some static hosts send .mjs with a non-JavaScript MIME type, which breaks module workers.
copy(path.join(pdfjs, "legacy/build/pdf.worker.min.mjs"), path.join(pdfjsOut, "pdf.worker.min.js"));
for (const dir of ["standard_fonts", "cmaps", "wasm", "iccs"]) {
  copy(path.join(pdfjs, dir), path.join(pdfjsOut, dir));
}

// Every wasm core variant: the worker picks SIMD or relaxed SIMD at runtime.
const tesseract = pkgDir("tesseract.js");
const tesseractCore = pkgDir("tesseract.js-core", createRequire(path.join(tesseract, "package.json")));
const tesseractOut = path.join(vendor, "tesseract");
copy(path.join(tesseract, "dist/worker.min.js"), path.join(tesseractOut, "worker.min.js"));
copy(tesseractCore, path.join(tesseractOut, "core"), (src) => statSync(src).isDirectory() || src.endsWith(".wasm.js"));
copy(path.join(pkgDir("@tesseract.js-data/eng"), "4.0.0_best_int/eng.traineddata.gz"), path.join(tesseractOut, "lang/eng.traineddata.gz"));

// Generated by samples/generate.py; skipped until they exist.
const samplesOut = path.join(publicDir, "samples");
rmSync(samplesOut, { recursive: true, force: true });
const samplesDir = path.join(repoRoot, "samples");
let copiedSamples = 0;
if (existsSync(samplesDir)) {
  for (const name of readdirSync(samplesDir)) {
    if (name.toLowerCase().endsWith(".pdf")) {
      copy(path.join(samplesDir, name), path.join(samplesOut, name));
      copiedSamples++;
    }
  }
  const receipts = path.join(samplesDir, "receipts");
  if (existsSync(receipts)) {
    for (const name of readdirSync(receipts)) {
      if (/\.(pdf|png|jpe?g)$/i.test(name)) {
        copy(path.join(receipts, name), path.join(samplesOut, "receipts", name));
        copiedSamples++;
      }
    }
  }
}

const mb = (n) => `${(n / 1024 / 1024).toFixed(1)} MB`;
console.log(
  `copy-vendor: pdfjs ${mb(sizeOf(pdfjsOut))}, tesseract ${mb(sizeOf(tesseractOut))}, ${copiedSamples} sample file(s)`,
);
