/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AUProfile */
        AUProfile: {
            /**
             * Covertype
             * @enum {string}
             */
            coverType: "hospital" | "extras" | "combined";
            /** @default null */
            hospital: components["schemas"]["HospitalCover"] | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "AU";
        };
        /** AnalyzeChunkResponse */
        AnalyzeChunkResponse: {
            /** Issues */
            issues?: components["schemas"]["Issue"][];
            /**
             * Pages
             * @description 1-based booklet page numbers covered by this chunk.
             */
            pages: number[];
            rows: components["schemas"]["ExtractedRows"];
            /** Traceid */
            traceId: string;
            usage: components["schemas"]["Usage"];
        };
        /** AssembleChunk */
        AssembleChunk: {
            /** Pages */
            pages: number[];
            rows: components["schemas"]["ExtractedRows"];
        };
        /** AssembleRequest */
        AssembleRequest: {
            /** Chunks */
            chunks: components["schemas"]["AssembleChunk"][];
            /**
             * Documentname
             * @default Uploaded booklet
             */
            documentName: string;
            /** Pagecount */
            pageCount: number;
            /**
             * Region
             * @enum {string}
             */
            region: "CA" | "AU";
        };
        /** AssembleResponse */
        AssembleResponse: {
            /** Issues */
            issues?: components["schemas"]["Issue"][];
            plan: components["schemas"]["Plan"];
        };
        /** Benefit */
        Benefit: {
            /** Categoryid */
            categoryId: string;
            /** Costshareids */
            costShareIds: string[];
            coverage: components["schemas"]["Coverage"];
            /** @default null */
            frequency: components["schemas"]["Frequency"] | null;
            /** Id */
            id: string;
            /** Itemcodes */
            itemCodes: string[];
            /** Keywords */
            keywords: string[];
            /** Limits */
            limits: components["schemas"]["Limit"][];
            /** Name */
            name: string;
            /**
             * Notes
             * @default null
             */
            notes: string | null;
            /**
             * Poolid
             * @default null
             */
            poolId: string | null;
            /** Requirements */
            requirements: string[];
            /** @default null */
            source: components["schemas"]["SourceRef"] | null;
            /** @default null */
            waitingPeriod: components["schemas"]["WaitingPeriod"] | null;
        };
        /** CAProfile */
        CAProfile: {
            /** @default null */
            hsa: components["schemas"]["HealthSpendingAccount"] | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "CA";
            /**
             * Province
             * @enum {string}
             */
            province: "AB" | "BC" | "MB" | "NB" | "NL" | "NS" | "NT" | "NU" | "ON" | "PE" | "QC" | "SK" | "YT";
            /**
             * Spouseplan
             * @default false
             */
            spousePlan: boolean;
        };
        /** Category */
        Category: {
            /** Benefits */
            benefits: components["schemas"]["Benefit"][];
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "paramedical" | "vision" | "dental" | "drugs" | "hospital" | "extras" | "medical_equipment" | "ambulance" | "travel" | "hsa" | "other";
            /** Name */
            name: string;
        };
        /**
         * ChatContext
         * @description Small, aliased context the browser sends with each chat turn (≤2 KB serialized).
         */
        ChatContext: {
            /** Categories */
            categories?: string[];
            /**
             * Currency
             * @enum {string}
             */
            currency: "CAD" | "AUD";
            /** Memberaliases */
            memberAliases?: string[];
            /**
             * Planname
             * @default null
             */
            planName: string | null;
            /**
             * Region
             * @enum {string}
             */
            region: "CA" | "AU";
            /**
             * Today
             * @description ISO date in the user's time zone.
             */
            today: string;
            /** Tz */
            tz: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /**
             * Activeagent
             * @default null
             */
            activeAgent: ("plan_claims" | "knowledge") | null;
            context: components["schemas"]["ChatContext"];
            /**
             * Messages
             * @description AI SDK UIMessage objects (id, role, parts).
             */
            messages: {
                [key: string]: unknown;
            }[];
        };
        /** Claim */
        Claim: {
            /** Attachments */
            attachments: components["schemas"]["ClaimAttachment"][];
            /** Createdat */
            createdAt: string;
            /**
             * Deadline
             * @default null
             */
            deadline: string | null;
            /** History */
            history: components["schemas"]["ClaimHistoryEntry"][];
            /** Id */
            id: string;
            /** Lines */
            lines: components["schemas"]["ClaimLine"][];
            /** @default null */
            outcome: components["schemas"]["ClaimOutcome"] | null;
            /** Patientmemberid */
            patientMemberId: string;
            /** Planid */
            planId: string;
            /**
             * Provider
             * @default null
             */
            provider: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "submitted" | "paid" | "partially_paid" | "rejected";
            /** Updatedat */
            updatedAt: string;
        };
        /** ClaimAttachment */
        ClaimAttachment: {
            /**
             * Kind
             * @default receipt
             * @enum {string}
             */
            kind: "receipt" | "eob" | "referral" | "other";
            /** Receiptid */
            receiptId: string;
        };
        /** ClaimHistoryEntry */
        ClaimHistoryEntry: {
            /**
             * Actor
             * @enum {string}
             */
            actor: "user" | "agent";
            /**
             * Agentname
             * @default null
             */
            agentName: string | null;
            /**
             * Agentversion
             * @default null
             */
            agentVersion: string | null;
            /**
             * At
             * @description ISO timestamp.
             */
            at: string;
            /**
             * Note
             * @default null
             */
            note: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "submitted" | "paid" | "partially_paid" | "rejected";
            /**
             * Traceid
             * @default null
             */
            traceId: string | null;
        };
        /** ClaimLine */
        ClaimLine: {
            /** Benefitid */
            benefitId: string;
            /** Chargedcents */
            chargedCents: number;
            /**
             * Description
             * @default null
             */
            description: string | null;
            /** Id */
            id: string;
            /**
             * Itemcode
             * @default null
             */
            itemCode: string | null;
            /**
             * Otherplanpaidcents
             * @default 0
             */
            otherPlanPaidCents: number;
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
            /**
             * Servicedate
             * Format: date
             */
            serviceDate: string;
        };
        /** ClaimOutcome */
        ClaimOutcome: {
            /**
             * Decidedon
             * @default null
             */
            decidedOn: string | null;
            /**
             * Note
             * @default null
             */
            note: string | null;
            /** Paidcents */
            paidCents: number;
        };
        /**
         * ClaimRules
         * @description Deadline: ``submissionDays`` after the service date, or ``daysAfterPeriodEnd`` after the end
         *     of the benefit period the service fell in. When both are set, the later date applies.
         */
        ClaimRules: {
            /**
             * Coordinationofbenefits
             * @default false
             */
            coordinationOfBenefits: boolean;
            /**
             * Daysafterperiodend
             * @default null
             */
            daysAfterPeriodEnd: number | null;
            /** Notes */
            notes: string[];
            /**
             * Receiptsrequired
             * @default true
             */
            receiptsRequired: boolean;
            /** @default null */
            source: components["schemas"]["SourceRef"] | null;
            /**
             * Submissiondays
             * @default null
             */
            submissionDays: number | null;
        };
        /**
         * CostShare
         * @description Something the member pays before or alongside the plan.
         *
         *     ``deductible`` (CA) and ``excess`` (AU hospital) are amounts per ``period``; ``copay`` is a fixed
         *     amount per service; ``coinsurance`` is informational because coverage percent already encodes it.
         */
        CostShare: {
            /**
             * Amountcents
             * @default null
             */
            amountCents: number | null;
            /** Appliestobenefitids */
            appliesToBenefitIds: string[];
            /** Appliestocategoryids */
            appliesToCategoryIds: string[];
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "deductible" | "excess" | "copay" | "coinsurance";
            /** Name */
            name: string;
            /**
             * Percent
             * @default null
             */
            percent: number | null;
            /** @default null */
            period: components["schemas"]["Period"] | null;
            /**
             * Scope
             * @default per_person
             * @enum {string}
             */
            scope: "per_person" | "per_family" | "per_policy";
            /** @default null */
            source: components["schemas"]["SourceRef"] | null;
        };
        /**
         * Coverage
         * @description How much of an eligible charge the plan pays.
         *
         *     - ``percent``: ``percent`` of the charge.
         *     - ``percent_capped``: ``percent`` of the charge, at most ``capCents`` per service.
         *     - ``fixed_per_service``: ``amountCents`` per service (never more than the charge).
         *     - ``per_diem``: ``amountCents`` per day (quantity = days).
         *     - ``schedule``: benefit looked up by item code in ``scheduleItems`` (AU extras), else ``percent``
         *       as a fallback when set.
         */
        Coverage: {
            /**
             * Amountcents
             * @default null
             */
            amountCents: number | null;
            /**
             * Capcents
             * @default null
             */
            capCents: number | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "percent" | "percent_capped" | "fixed_per_service" | "per_diem" | "schedule";
            /**
             * Percent
             * @default null
             */
            percent: number | null;
            /** Scheduleitems */
            scheduleItems: components["schemas"]["ScheduleItem"][];
            /**
             * Schedulenote
             * @default null
             */
            scheduleNote: string | null;
        };
        /** ErrorBody */
        ErrorBody: {
            /**
             * Code
             * @enum {string}
             */
            code: "payload_too_large" | "pii_detected" | "unsafe_image" | "rate_limited" | "budget_exhausted" | "ai_disabled" | "invalid_request" | "unsupported_media_type" | "page_cap_exceeded" | "booklet_cap_exceeded" | "upstream_error" | "content_filtered" | "prompt_injection" | "internal_error";
            /**
             * Details
             * @default null
             */
            details: components["schemas"]["PiiDetectedDetail"][] | null;
            /** Message */
            message: string;
            /**
             * Retryafterseconds
             * @default null
             */
            retryAfterSeconds: number | null;
            /**
             * Traceid
             * @default null
             */
            traceId: string | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** ExBenefitRow */
        ExBenefitRow: {
            /** Benefit Name */
            benefit_name: string;
            /** Category Kind */
            category_kind: string | null;
            /** Category Name */
            category_name: string;
            /** Coverage Amount */
            coverage_amount: number | null;
            /** Coverage Cap Amount */
            coverage_cap_amount: number | null;
            /** Coverage Kind */
            coverage_kind: ("percent" | "percent_capped" | "fixed_per_service" | "per_diem" | "schedule") | null;
            /** Coverage Percent */
            coverage_percent: number | null;
            /** Frequency Count */
            frequency_count: number | null;
            /** Frequency Period Kind */
            frequency_period_kind: string | null;
            /** Frequency Period Months */
            frequency_period_months: number | null;
            /**
             * Item Codes
             * @description Comma-separated item codes, if the table lists them.
             */
            item_codes: string | null;
            /**
             * Keywords
             * @description Comma-separated synonyms, e.g. 'RMT, massage therapy'.
             */
            keywords: string | null;
            /** Limit Period Kind */
            limit_period_kind: string | null;
            /** Limit Period Months */
            limit_period_months: number | null;
            /** Limit Scope */
            limit_scope: ("per_person" | "per_family" | "per_policy") | null;
            /** Limit Unit */
            limit_unit: ("dollars" | "visits" | "items" | "days" | "hours") | null;
            /** Limit Value */
            limit_value: number | null;
            meta: components["schemas"]["RowMeta"];
            /** Notes */
            notes: string | null;
            /** Page */
            page: number;
            /** Pool Name */
            pool_name: string | null;
            /** Quote */
            quote: string;
            /** Requirements */
            requirements: string | null;
            /** Row Id */
            row_id: string;
            /** Waiting Period Months */
            waiting_period_months: number | null;
        };
        /** ExCostShareRow */
        ExCostShareRow: {
            /** Amount */
            amount: number | null;
            /**
             * Applies To
             * @description Comma-separated category or benefit names.
             */
            applies_to: string | null;
            /** Kind */
            kind: ("deductible" | "excess" | "copay" | "coinsurance") | null;
            meta: components["schemas"]["RowMeta"];
            /** Name */
            name: string;
            /** Page */
            page: number;
            /** Percent */
            percent: number | null;
            /** Period Kind */
            period_kind: string | null;
            /** Quote */
            quote: string;
            /** Row Id */
            row_id: string;
            /** Scope */
            scope: ("per_person" | "per_family" | "per_policy") | null;
        };
        /** ExHeaderRow */
        ExHeaderRow: {
            /** Benefit Period Kind */
            benefit_period_kind: ("benefit_year" | "policy_anniversary") | null;
            /** Benefit Period Start Month */
            benefit_period_start_month: number | null;
            /** Cover Type */
            cover_type: ("hospital" | "extras" | "combined") | null;
            /** Currency */
            currency: ("CAD" | "AUD") | null;
            /** Effective Date */
            effective_date: string | null;
            /** Hospital Plus */
            hospital_plus: boolean | null;
            /** Hospital Tier */
            hospital_tier: ("gold" | "silver" | "bronze" | "basic") | null;
            /** Hsa Annual Credit */
            hsa_annual_credit: number | null;
            /** Hsa Carry Forward Years */
            hsa_carry_forward_years: number | null;
            /** Insurer */
            insurer: string | null;
            meta: components["schemas"]["RowMeta"];
            /** Page */
            page: number;
            /** Plan Name */
            plan_name: string | null;
            /** Province */
            province: string | null;
            /** Quote */
            quote: string;
            /** Row Id */
            row_id: string;
        };
        /** ExHospitalCategoryRow */
        ExHospitalCategoryRow: {
            meta: components["schemas"]["RowMeta"];
            /** Name */
            name: string;
            /** Page */
            page: number;
            /** Quote */
            quote: string;
            /** Row Id */
            row_id: string;
            /** Status */
            status: ("covered" | "restricted" | "excluded") | null;
        };
        /** ExPoolRow */
        ExPoolRow: {
            /**
             * Benefit Names
             * @description Comma-separated benefit names sharing this maximum.
             */
            benefit_names: string | null;
            /** Limit Unit */
            limit_unit: ("dollars" | "visits" | "items" | "days" | "hours") | null;
            /** Limit Value */
            limit_value: number | null;
            meta: components["schemas"]["RowMeta"];
            /** Page */
            page: number;
            /** Period Kind */
            period_kind: string | null;
            /** Period Months */
            period_months: number | null;
            /** Pool Name */
            pool_name: string;
            /** Quote */
            quote: string;
            /** Row Id */
            row_id: string;
            /** Scope */
            scope: ("per_person" | "per_family" | "per_policy") | null;
        };
        /** ExRuleRow */
        ExRuleRow: {
            /** Deadline Basis */
            deadline_basis: ("service_date" | "period_end") | null;
            /** Deadline Days */
            deadline_days: number | null;
            meta: components["schemas"]["RowMeta"];
            /** Page */
            page: number;
            /** Quote */
            quote: string;
            /** Row Id */
            row_id: string;
            /**
             * Rule Kind
             * @enum {string}
             */
            rule_kind: "submission_deadline" | "receipts_required" | "coordination_of_benefits" | "other";
            /** Text */
            text: string | null;
        };
        /** ExtractedRows */
        ExtractedRows: {
            /** Benefits */
            benefits?: components["schemas"]["ExBenefitRow"][];
            /** Cost Shares */
            cost_shares?: components["schemas"]["ExCostShareRow"][];
            /** Header */
            header?: components["schemas"]["ExHeaderRow"][];
            /** Hospital Categories */
            hospital_categories?: components["schemas"]["ExHospitalCategoryRow"][];
            /** Pools */
            pools?: components["schemas"]["ExPoolRow"][];
            /** Rules */
            rules?: components["schemas"]["ExRuleRow"][];
        };
        /** FieldConfidence */
        FieldConfidence: {
            /** Confidence */
            confidence: number;
            /**
             * Source
             * @description CU source string, e.g. D(1,0.5,1.2,...).
             * @default null
             */
            source: string | null;
        };
        /**
         * Frequency
         * @description At most ``count`` services per ``period`` (e.g. one eye exam every 24 months).
         */
        Frequency: {
            /** Count */
            count: number;
            period: components["schemas"]["Period"];
            /**
             * Scope
             * @default per_person
             * @enum {string}
             */
            scope: "per_person" | "per_family" | "per_policy";
        };
        /** HealthResponse */
        HealthResponse: {
            /** Agentversions */
            agentVersions?: {
                [key: string]: string;
            };
            /** Aienabled */
            aiEnabled: boolean;
            /**
             * Aimode
             * @enum {string}
             */
            aiMode: "live" | "fake" | "off";
            /**
             * Budgetremainingpct
             * @description Lowest remaining share across demo namespaces.
             */
            budgetRemainingPct: number;
            /** Budgets */
            budgets?: {
                [key: string]: number;
            };
            /** Ok */
            ok: boolean;
            /** Version */
            version: string;
        };
        /** HealthSpendingAccount */
        HealthSpendingAccount: {
            /** Annualcreditcents */
            annualCreditCents: number;
            /**
             * Carryforwardyears
             * @default 0
             */
            carryForwardYears: number;
        };
        /** HospitalCategory */
        HospitalCategory: {
            /** Name */
            name: string;
            /** @default null */
            source: components["schemas"]["SourceRef"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "covered" | "restricted" | "excluded";
        };
        /** HospitalCover */
        HospitalCover: {
            /** Categories */
            categories: components["schemas"]["HospitalCategory"][];
            /** @default null */
            excess: components["schemas"]["HospitalExcess"] | null;
            /**
             * Plus
             * @default false
             */
            plus: boolean;
            /**
             * Tier
             * @enum {string}
             */
            tier: "gold" | "silver" | "bronze" | "basic";
        };
        /** HospitalExcess */
        HospitalExcess: {
            /** Amountcents */
            amountCents: number;
            /**
             * Maxperyearcents
             * @default null
             */
            maxPerYearCents: number | null;
            /**
             * Per
             * @enum {string}
             */
            per: "admission" | "year";
        };
        /** Issue */
        Issue: {
            /**
             * Category
             * @description PII category, never the matched value.
             * @default null
             */
            category: string | null;
            /**
             * Code
             * @enum {string}
             */
            code: "pii_advisory" | "prompt_injection" | "page_excluded" | "page_irrelevant" | "unsupported_row" | "low_confidence" | "ungrounded_quote" | "verifier_rounds_exhausted" | "duplicate_removed" | "unlinked_pool" | "unlinked_cost_share" | "ocr_empty" | "field_missing" | "content_filtered" | "assumed_default";
            /** Message */
            message: string;
            /**
             * Page
             * @default null
             */
            page: number | null;
            /**
             * Rowid
             * @default null
             */
            rowId: string | null;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "error";
        };
        /**
         * Limit
         * @description A maximum. ``unit == "cents"`` means ``value`` is money in cents; otherwise a count.
         */
        Limit: {
            period: components["schemas"]["Period"];
            /**
             * Scope
             * @default per_person
             * @enum {string}
             */
            scope: "per_person" | "per_family" | "per_policy";
            /**
             * Unit
             * @enum {string}
             */
            unit: "cents" | "visits" | "items" | "days" | "hours";
            /** Value */
            value: number;
        };
        /**
         * LimitPool
         * @description A combined maximum shared by several benefits (e.g. paramedical combined $1,500).
         */
        LimitPool: {
            /** Benefitids */
            benefitIds: string[];
            /** Id */
            id: string;
            limit: components["schemas"]["Limit"];
            /** Name */
            name: string;
            /** @default null */
            source: components["schemas"]["SourceRef"] | null;
        };
        /** Member */
        Member: {
            /**
             * Alias
             * @description Alias token such as [MEMBER_A]; the raw name never leaves the browser.
             */
            alias: string;
            /** Id */
            id: string;
            /**
             * Relationship
             * @enum {string}
             */
            relationship: "self" | "spouse" | "child" | "dependent";
        };
        /**
         * Period
         * @description A window that limits, frequencies and deductibles reset on.
         *
         *     - ``benefit_year``: calendar-style year starting ``startMonth``/``startDay`` (Jan 1 when omitted).
         *     - ``policy_anniversary``: year starting on the plan's ``effectiveDate`` anniversary.
         *     - ``rolling_months``: any ``months``-long window ending on the service date.
         *     - ``consecutive_benefit_years``: ``years`` benefit years in a row (e.g. glasses every 2 years).
         *     - ``lifetime``: never resets.
         *     - ``per_visit`` / ``per_admission``: applies to each visit or hospital admission.
         */
        Period: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "benefit_year" | "policy_anniversary" | "rolling_months" | "consecutive_benefit_years" | "lifetime" | "per_visit" | "per_admission";
            /**
             * Months
             * @default null
             */
            months: number | null;
            /**
             * Startday
             * @default null
             */
            startDay: number | null;
            /**
             * Startmonth
             * @default null
             */
            startMonth: number | null;
            /**
             * Years
             * @default null
             */
            years: number | null;
        };
        /** PiiDetectedDetail */
        PiiDetectedDetail: {
            /** Category */
            category: string;
            /**
             * Page
             * @default null
             */
            page: number | null;
            /**
             * Polygon
             * @description Page-relative polygon in inches (CU word polygon), if available.
             * @default null
             */
            polygon: number[] | null;
        };
        /** Plan */
        Plan: {
            benefitPeriod: components["schemas"]["Period"];
            /** Categories */
            categories: components["schemas"]["Category"][];
            claimRules: components["schemas"]["ClaimRules"];
            /** Costshares */
            costShares: components["schemas"]["CostShare"][];
            /**
             * Currency
             * @enum {string}
             */
            currency: "CAD" | "AUD";
            /** @default null */
            document: components["schemas"]["PlanDocument"] | null;
            /**
             * Effectivedate
             * @default null
             */
            effectiveDate: string | null;
            /** Id */
            id: string;
            /**
             * Identifiers
             * @description Alias tokens for policy/group/certificate numbers, e.g. [POLICY_1].
             */
            identifiers: string[];
            /** Insurer */
            insurer: string;
            /** Limitpools */
            limitPools: components["schemas"]["LimitPool"][];
            /** Members */
            members: components["schemas"]["Member"][];
            /** Planname */
            planName: string;
            /** Profile */
            profile: components["schemas"]["CAProfile"] | components["schemas"]["AUProfile"];
            /**
             * Region
             * @enum {string}
             */
            region: "CA" | "AU";
            /**
             * Schemaversion
             * @default 1
             * @constant
             */
            schemaVersion: 1;
        };
        /** PlanDocument */
        PlanDocument: {
            /**
             * Extractedat
             * @default null
             */
            extractedAt: string | null;
            /**
             * Isdemo
             * @default false
             */
            isDemo: boolean;
            /** Name */
            name: string;
            /** Pagecount */
            pageCount: number;
        };
        /** Receipt */
        Receipt: {
            /**
             * Currency
             * @default null
             */
            currency: ("CAD" | "AUD") | null;
            /**
             * Insurerpaidcents
             * @default null
             */
            insurerPaidCents: number | null;
            /**
             * Providername
             * @default null
             */
            providerName: string | null;
            /**
             * Providerregistrationno
             * @default null
             */
            providerRegistrationNo: string | null;
            /**
             * Providertype
             * @default null
             */
            providerType: string | null;
            /** Servicelines */
            serviceLines: components["schemas"]["ReceiptLine"][];
            /**
             * Totalcents
             * @default null
             */
            totalCents: number | null;
        };
        /** ReceiptAnalyzeResponse */
        ReceiptAnalyzeResponse: {
            /** Fieldconfidence */
            fieldConfidence?: {
                [key: string]: components["schemas"]["FieldConfidence"];
            };
            /** Issues */
            issues?: components["schemas"]["Issue"][];
            receipt: components["schemas"]["Receipt"];
            /** Traceid */
            traceId: string;
            usage: components["schemas"]["Usage"];
        };
        /** ReceiptLine */
        ReceiptLine: {
            /**
             * Amountcents
             * @default null
             */
            amountCents: number | null;
            /**
             * Description
             * @default null
             */
            description: string | null;
            /**
             * Itemcode
             * @default null
             */
            itemCode: string | null;
            /**
             * Quantity
             * @default null
             */
            quantity: number | null;
            /**
             * Servicedate
             * @default null
             */
            serviceDate: string | null;
        };
        /**
         * RowMeta
         * @description Per-row provenance attached after verification and deterministic grounding.
         */
        RowMeta: {
            /** Confidence */
            confidence: number;
            /**
             * Grounded
             * @description True when the quote fuzzy-matches the page markdown.
             */
            grounded: boolean;
            /**
             * Kind
             * @enum {string}
             */
            kind: "header" | "benefit" | "pool" | "cost_share" | "rule" | "hospital_category";
            /** Page */
            page: number;
            /** Rowid */
            rowId: string;
            /**
             * Verifierverdict
             * @default null
             */
            verifierVerdict: ("supported" | "corrected" | "unsupported") | null;
        };
        /** ScheduleItem */
        ScheduleItem: {
            /** Benefitcents */
            benefitCents: number;
            /** Description */
            description: string;
            /** Itemcode */
            itemCode: string;
        };
        /**
         * SourceRef
         * @description Where a value came from in the (redacted) booklet.
         */
        SourceRef: {
            /** Confidence */
            confidence: number;
            /** Page */
            page: number;
            /** Quote */
            quote: string;
            /**
             * Verifierverdict
             * @default null
             */
            verifierVerdict: ("supported" | "corrected" | "unsupported") | null;
        };
        /** Usage */
        Usage: {
            /** Bystepms */
            byStepMs?: {
                [key: string]: number;
            };
            /**
             * Contentsafetyrecords
             * @default 0
             */
            contentSafetyRecords: number;
            /**
             * Cupages
             * @default 0
             */
            cuPages: number;
            /**
             * Estimatedcostusd
             * @default 0
             */
            estimatedCostUsd: number;
            /**
             * Inputtokens
             * @default 0
             */
            inputTokens: number;
            /**
             * Languagerecords
             * @default 0
             */
            languageRecords: number;
            /**
             * Outputtokens
             * @default 0
             */
            outputTokens: number;
        };
        /** WaitingPeriod */
        WaitingPeriod: {
            /** Months */
            months: number;
            /**
             * Note
             * @default null
             */
            note: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
